# Demonstrate Arithmetic operator
a=float(input("Enter a value: "))
b=float(input("Enter a value: "))
print("="*30)
print("%f + %f = %f"%(a,b,a+b))
print("%f - %f = %f"%(a,b,a-b))
print("%f * %f = %f"%(a,b,a*b))
print("%f / %f = %f"%(a,b,a/b))
print("%f // %f = %f"%(a,b,a//b))
print("%f & %f = %f"%(a,b,a%b))
print("%f ** %f = %f"%(a,b,a**b))
print("="*30)