class student:
    crs = input("Enter course name: ")
    city = input("Enter City name: ")

s1 = student()
s2 = student()
print("---------------")
print("content s1 = ",s1.__dict__)
print("content s2 = ",s2.__dict__)
print("-----------------------")
s1.sno = int(input("Enter first student mark: "))
s1.sname = input("Enter First student name: ")
s1.mark = float(input("Enter First student mark: "))

s2.sno = int(input("Enter second student mark: "))
s2.sname = input("Enter second student name: ")
s2.mark = float(input("Enter secons student mark: "))

print("content s1 = ",s1.__dict__)
print("content s2 = ",s2.__dict__)
print("-----------------------")
print("S1 value")
print("student number: {}".format(s1.sno))
print("student name: {}".format(s1.sname))
print("student mark: {}".format(s1.mark))
print("Student Course = {}".format(student.crs))
print("-----------------------")
print("S2 value")
print("student number: {}".format(s2.sno))
print("student name: {}".format(s2.sname))
print("student mark: {}".format(s2.mark))
print("Student Course = {}".format(student.crs))
print("---------------------------")
# print("S1 value")
# for k,v in s1.__dict__.items():
#     print("{} ====> {}".format(k,v))
# print("----------------------------")
# print("S2 value")
# for k,v in s2.__dict__.items():
#     print("{} ====> {}".format(k,v))
# print("------------------------")